### ISSUE TITLE
首页-概览-显示问题

### ISSUE THREAD

**Issue by ParnDeedlit** [MapGIS/WebClient-JavaScript#1]
🚨 请仔细查看下面的描述

**Bug描述**
http://localhost:8899/ui/total-explore.html
这个网页是无效网页，请下架

**重现步骤**
详细重现步骤:
1. 进入主页
2. 点击概览
3. 选择“浏览器兼容性”选项
![tim 20180911110516](https://user-images.githubusercontent.com/23654117/45335702-30f5f900-b5b3-11e8-83fb-810817c78b1a.png)

4. 看见错误网页

**预计结果/错误结果**
http://localhost:8899/ui/total-explore.html

**截图**
![tim 20180911110522](https://user-images.githubusercontent.com/23654117/45335708-33585300-b5b3-11e8-84e4-9fb58c26c108.png)

**Desktop-桌面浏览器 (请补充下面信息):**
 - OS（操作系统）: [e.g. Win7]
 - Browser（浏览器） [e.g. chrome]
 - Version（版本） [e.g.  67.0.3396.99]

**额外备注**
无

详细维护人员：
WebClient展示页面：研究院-陈琪
IGServer：邬俊惠
DataStore/DataView：基础平台/创新中心-潘卓然  
> 微信：18064124285 电话：18064124285 qq：398809724 邮箱：panzhuoran.parndeedlit@mapgis.com 飞秋：潘卓然ParnDeedlit

详细四大引擎：
leaflet：平台二次开发-朱鹏飞
mapboxgl：基础平台/创新中心-潘卓然
cesium：基础平台-韩彦生
openlayers：IGServer-黄漭

💔 感谢大家的共同维护！

**Comment by CQ-bliss** [comment]
该问题已解决，不在显示浏览器兼容性页面。
