### ISSUE TITLE
Openlayers3中，如何判断多边形点坐是否为连续的面

### ISSUE THREAD

**Issue by abbysiqi** [MapGIS/WebClient-JavaScript#18]
如下图所示，需要左侧效果，如果是右测效果该如何判断
![123](https://user-images.githubusercontent.com/5541373/50213175-cc1f1b80-03b7-11e9-8f14-27f9e167eab9.png)

**Comment by ParnDeedlit** [comment]
# Turfjs
>  Turfjs是前端空间分析脚本，与任何第三方地图脚本如openlayers，leaflet，mapboxgl可以共用

## 问题描述
[Turfjs在线帮助文档](http://turfjs.org/docs/#kinks)
该问题的本质实际上是自相交问题 intersection，在turfjs中使用kinks判断自相交的点的数量既可以判断是否自相交
![tim 20181220182946](https://user-images.githubusercontent.com/23654117/50279647-45387480-0485-11e9-8de1-e786cbdd96b5.png)


## 示例代码
``` js
var poly = turf.polygon([[
  [-12.034835, 8.901183],
  [-12.060413, 8.899826],
  [-12.03638, 8.873199],
  [-12.059383, 8.871418],
  [-12.034835, 8.901183]
]]);

var kinks = turf.kinks(poly);

```

**Comment by abbysiqi** [comment]
已按照提示解决，感谢~
