### ISSUE TITLE
测试功能需求

### ISSUE THREAD

**Issue by ParnDeedlit** [MapGIS/WebClient-JavaScript#2]
**您的功能请求是否与问题有关？ 请描述一下。**
怎么向WebClient项目提交新的Bug报告，以及向谁提交Bug问题。

**描述你想要的解决方案**
出了问题能够责任到人。

**描述您考虑过的替代方案**
在网页四大引擎选择界面的底部有类似的维护人，但是没有对应的连接，是否能提供完整的详细的功能维护列表。
http://client.snanyun.com:8899/ui/gallery-leaflet.html#analysis-intersect

http://client.snanyun.com:8899/ui/total-select.html

**附加背景**
![tim 20180912090607](https://user-images.githubusercontent.com/23654117/45395975-462e5e80-b66b-11e8-8f0a-84244a1ead61.png)
![tim 20180912090801](https://user-images.githubusercontent.com/23654117/45395993-6bbb6800-b66b-11e8-8328-e4bae38a4dc9.png)

> `我怎么联系上图中的人以及后续如何跟进呢??`

**Comment by CQ-bliss** [comment]
此页面已经设计成功
