### ISSUE TITLE
中国大陆地区无法使用谷歌地图服务问题

### ISSUE THREAD

**Issue by liuqun** [MapGIS/WebClient-JavaScript#31]
website中的大量例子（[约70个](https://github.com/MapGIS/WebClient-JavaScript/search?l=HTML&q=appendGoogleMapExt)）依赖谷歌地图服务作为卫星底图：`http://mt{s}.google.cn/vt/lyrs={type}&hl=zh-CN${offsetLabel}&x={x}&y={y}&z={z}&s=Galileo`

然而国内无法访问mt{s}.google.cn，能否从例子代码中移除谷歌服务改为其他地图？
https://github.com/liuqun/WebClient-JavaScript/commit/eda24abead8e249afcff3c880b72054d1dbdc31d

也可以考虑修改`appendGoogleMapExt()`和`appendGoogleMap()`内部url，指向其他坐标无偏卫星地图，例如天地图

**Comment by ParnDeedlit** [comment]
好的 目前已经安排统一替换

**Comment by ParnDeedlit** [comment]
1. SDK 新增 OSM接口 https://github.com/MapGIS/WebClient-JavaScript/commit/fb2eab5536da86e66ad0535d7939b374b5014fbb
2. 站点 将之前的谷歌底图替换成 OSM地图 https://github.com/MapGIS/WebClient-JavaScript/commit/e73350ed7b6bb12d12dc1db497849b8ec3d0607e
