### ISSUE TITLE
Linux下部署website发现文件夹名大小写敏感导致bug

### ISSUE THREAD

**Issue by liuqun** [MapGIS/WebClient-JavaScript#32]
在CentOS 7.9下使用nginx部署website发现
include-cesium-local.js GET static/libs/cdn/cesium/MapGIS/Css/mapgis.css net::ERR_ABORTED 404 (Not Found)

https://github.com/MapGIS/WebClient-JavaScript/blob/35efa9cbbef7cb455b5fca54a1a64f1fffa26de9/website/public/static/libs/include-cesium-local.js#L53
Bug原因：
`Css`应改为小写`css`，Windows+IIS不区分大小写不会触发bug，CentOS下的nginx默认对文件名大小写敏感

此Bug影响"Cesium--三维空间分析--动画漫游" （`demo/cesium/analysis/analysis-animation.htm`）

**Comment by ParnDeedlit** [comment]
好的 谢谢发现

**Comment by ParnDeedlit** [comment]
https://github.com/MapGIS/WebClient-JavaScript/commit/38eccc28cf20db3e5d33280c38fdeddba91e28fe  修复完毕
