### ISSUE TITLE
npm run service-release 报错: 因缺少依赖包qs而导致编译失败

### ISSUE THREAD

**Issue by liuqun** [MapGIS/WebClient-JavaScript#34]
在根目录下执行npm编译service模块报错
```
npm install
npm run service-release
```

https://github.com/MapGIS/WebClient-JavaScript/blob/da94ff6b91981067cd011f609068f85394e3c80b/src/service/datastore/ServiceBase.js#L1

顶层package.json中因缺少qs而导致编译失败

但是发现src/service/package.json中已经包含依赖包qs了，所以是不是编译顶层项目之前还要先到src/service子目录中手动执行一次`npm install`？

顶层的README.md文档只要求开发者去website子目录中执行操作，没有提及src/service子目录

**Comment by ParnDeedlit** [comment]
https://github.com/MapGIS/WebClient-JavaScript/commit/771ce5f2b310b980cec9d88ae1792659f1febf19
已更改到顶层目录中
