### ISSUE TITLE
Bug: 天地图URL域名错误

### ISSUE THREAD

**Issue by liuqun** [MapGIS/WebClient-JavaScript#37]
https://github.com/MapGIS/WebClient-JavaScript/blob/98db6161d0d9509daee3a40fe67932257107c9a4/src/cesiumjs/layer/ThirdPartyLayer.js#L204
https://github.com/MapGIS/WebClient-JavaScript/blob/98db6161d0d9509daee3a40fe67932257107c9a4/src/cesiumjs/layer/ThirdPartyLayer.js#L256

`tianditu.gov.cn.`末尾多了一个点号

@MarsQiu

**Comment by MarsQiu** [comment]
此问题已经修改，谢谢指出 @liuqun
