### ISSUE TITLE
WebClient中关于OpenLayer  API的添加与说明

### ISSUE THREAD

**Issue by Sumoolx** [MapGIS/WebClient-JavaScript#4]
**您的功能请求是否与问题有关？ 请描述一下。**
在使用Openlayer获取OGC地图服务的时候在WebClient上找不到相应的API , 例如 Zondy.Map.ArcGISLayer

**描述你想要的解决方案**
WebClient上添加关于Openlayer开发的API

**描述您考虑过的替代方案**
None

**附加背景**
例如  开发过程中想要了解Zondy.Map.ArcGISLayer相关用法

![image](https://user-images.githubusercontent.com/41618753/45674006-c159ae00-bb5e-11e8-90df-4ad1051cb559.png)

**Comment by ParnDeedlit** [comment]
# 总体描述
该问题已解决，请参考[webclient-openlayers-api](http://client.snanyun.com:8899/api/openlayers/Zondy.Map.ArcGISLayer.html)

# 源代码与参数描述
[source code](
http://client.snanyun.com:8899/api/openlayers/openlayers_mapgislayerForOL_3rdLayer.js.html#sunlight-1-line-1233)


[枚举参数]（http://client.snanyun.com:8899/api/openlayers/global.html#ArcGISLayerType）
