### ISSUE TITLE
空间分析

### ISSUE THREAD

**Issue by zhaoxpeng** [MapGIS/WebClient-JavaScript#5]
🚨 请仔细查看下面的描述

**Bug描述**
叠加分析只将范围线形成的多边形高亮显示，并没有看到叠加分析的结果。

**重现步骤**
详细重现步骤:

**预计结果/错误结果**
请描述预计的错误结果.

**截图**
如果必要，请提供截图描述信息.
![image](https://user-images.githubusercontent.com/34622531/45738422-f596a280-bc22-11e8-9894-b97f571c7ae6.png)

**Desktop-桌面浏览器 (请补充下面信息):**
 - OS（操作系统）: [e.g. iOS]
 - Browser（浏览器） [e.g. chrome, safari]
 - Version（版本） [e.g. 22]

**Smartphone-移动端 (请补充下面信息):**
 - Device（移动设备）: [e.g. iPhone6]
 - OS（操作系统）: [e.g. iOS8.1]
 - Browser（浏览器） [e.g. stock browser, safari]
 - Version（版本） [e.g. 22]

**额外备注**
添加问题的额外备注信息.

详细维护人员：
IGServer：邬俊惠
DataStore/DataView：基础平台/创新中心-潘卓然  
> 微信：18064124285 电话：18064124285 qq：398809724 邮箱：panzhuoran.parndeedlit@mapgis.com 飞秋：潘卓然ParnDeedlit

详细四大引擎：
leaflet：平台二次开发-朱鹏飞
mapboxgl：基础平台/创新中心-潘卓然
cesium：基础平台-韩彦生
openlayers：IGServer-黄漭

💔 感谢大家的共同维护！

**Comment by ParnDeedlit** [comment]
# 错误原因
由于该网页使用的机器是阿里云上的公共机器，访问量较大，一旦处理过多的空间分析任务，服务器的压力过大，导致工作流程序崩溃。

> 该问题是并发量过大导致的计算器的计算`内存溢出`，工作流程序`崩溃`，在正常的本地测试环境下是`正常`的。

# 解决方案
该计算密集型操作。本地测试通过，如果不超出机器的内存边界，是不会大量崩溃的
