### ISSUE TITLE
关于ZondyWebClient调用OGC服务的一些建议

### ISSUE THREAD

**Issue by Sumoolx** [MapGIS/WebClient-JavaScript#9]
**您的功能请求是否与问题有关？ 请描述一下。**
1.MapGIS发布地图服务前应该将高斯投影数据做投影变换。
2.ArcGIS发布地图服务在属性中更改投影变换。
3.关于调用ArcServer发布的地图服务调用不显示问题应该如何处理?投影变换后发布的ArcGIS服务还是不能在WebClient里面调用，不知是否是layers参数和version参数导致。若是，应该如何正确提供ArcGIS发布的服务的版本。

**描述你想要的解决方案**
我在本地部署的ArcGIS以及ArcServer(均为10.3版本)  发布的地图服务不可以在WebClient里面调用成功。
是否可以在公司内部服务器上部署一套10.3环境，并发布服务，然后提供Webclient展示案例.

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by ParnDeedlit** [comment]
下面的问题请参考 #8 
1.MapGIS发布地图服务前应该将高斯投影数据做投影变换。
2.ArcGIS发布地图服务在属性中更改投影变换。

**Comment by ParnDeedlit** [comment]
3.关于调用ArcServer发布的地图服务调用不显示问题应该如何处理?投影变换后发布的ArcGIS服务还是不能在WebClient里面调用，不知是否是layers参数和version参数导致。若是，应该如何正确提供ArcGIS发布的服务的版本。

# 核心问题
> 经过测试，之前的webclient的版本是可以正常加载arcserver的ogc服务的，真正的原因估计还是在你那边发布地图服务的时候没有进行类似 中地数码-地图文档-动态投影的操作

## 正常加载arcgis ogc的示例

[WebClient加载ArcServer在线示例](http://client.snanyun.com:8899/ui/gallery-leaflet.html#arcserver-arcserver_ogc_4326) 该示例与之前的  **地图功能-地图地图-arcgis地图显示**  的示例一样

请详细检查地理位置与操作系是否是经纬度  4326 4490 4214都是经纬度
![tim 20181019175420](https://user-images.githubusercontent.com/23654117/47211458-0ffda080-d3c8-11e8-8a61-d27f6a1a231d.png)
![tim 20181019175925](https://user-images.githubusercontent.com/23654117/47211892-4daef900-d3c9-11e8-99f9-eab87185103f.png)

**Comment by ParnDeedlit** [comment]
### arcgis wms服务

> [ArcGIS服务](http://222.247.40.204:6080/arcgis/rest/services/hnbianjiexian/MapServer)

> > 点击上面的网页，弹出对应的网页如下所示：


![igserver](../demo/leaflet/markdown/map/mapdisplay/arcserver.png)

1. `关注上面的红色框，第一个红色框需要注意的是一定要发布对应的WMS服务即出现“WMS”关键字眼`
    > 如果没有WMS选项，请先发布个WMS服务，要不然webclient脚本调用不了
2. 点击wms，获得对应的链接 http://222.247.40.204:6080/arcgis/services/hnbianjiexian/MapServer/WMSServer?request=GetCapabilities&service=WMS
3. 将上面链接 `？` 号之前的地址复制到脚本里面
    ``` javascript
    var Layer = L.tileLayer.wms('http://222.247.40.204:6080/arcgis/services/hnbianjiexian/MapServer/WMSServer?', {
        //图层序列号
        layers: '0,1,2',
        //wms版本号
        version: '1.3.0',
        //设置地图不连续显示
        noWrap:true
    }).addTo(map);
    ```
4. 设置对应的中心点，请注意 `纬度在前面， 经度在后面` 与正常的习惯相反
5. 设置对应的显示级别

**Comment by ParnDeedlit** [comment]
### arcgis wms服务

> [ArcGIS服务](http://222.247.40.204:6080/arcgis/rest/services/hnbianjiexian/MapServer)

> > 点击上面的网页，弹出对应的网页如下所示：

![arcserver](https://user-images.githubusercontent.com/23654117/47277101-3d786300-d5ef-11e8-97eb-c19bc231eada.png)


1. `关注上面的红色框，第一个红色框需要注意的是一定要发布对应的WMS服务即出现“WMS”关键字眼`
    > 如果没有WMS选项，请先发布个WMS服务，要不然webclient脚本调用不了
2. 点击wms，获得对应的链接 http://222.247.40.204:6080/arcgis/services/hnbianjiexian/MapServer/WMSServer?request=GetCapabilities&service=WMS
3. 将上面链接 `？` 号之前的地址复制到脚本里面
    ``` javascript
    var Layer = L.tileLayer.wms('http://222.247.40.204:6080/arcgis/services/hnbianjiexian/MapServer/WMSServer?', {
        //图层序列号
        layers: '0,1,2',
        //wms版本号
        version: '1.3.0',
        //设置地图不连续显示
        noWrap:true
    }).addTo(map);
    ```
4. 设置对应的中心点，请注意 `纬度在前面， 经度在后面` 与正常的习惯相反
5. 设置对应的显示级别

**Comment by ParnDeedlit** [comment]
### arcgis wms服务

> [ArcGIS服务](http://222.247.40.204:6080/arcgis/rest/services/hnbianjiexian/MapServer)

> > 点击上面的网页，弹出对应的网页如下所示：
![arcserver](https://user-images.githubusercontent.com/23654117/47279148-ad8fe480-d601-11e8-9d48-a4347b5f9ee3.png)


1. `关注上面的红色框，第一个红色框需要注意的是一定要发布对应的WMS服务即出现“WMS”关键字眼`
    > 如果没有WMS选项，请先发布个WMS服务，要不然webclient脚本调用不了
2. 点击wms，获得对应的链接 http://222.247.40.204:6080/arcgis/services/hnbianjiexian/MapServer/WMSServer?request=GetCapabilities&service=WMS
3. 将上面链接 `？` 号之前的地址复制到脚本里面
    ``` javascript
    var Layer = L.tileLayer.wms('http://222.247.40.204:6080/arcgis/services/hnbianjiexian/MapServer/WMSServer?', {
        //图层序列号
        layers: '0,1,2',
        //wms版本号
        version: '1.3.0',
        //设置地图不连续显示
        noWrap:true
    }).addTo(map);
    ```
4. 设置对应的中心点，请注意 `纬度在前面， 经度在后面` 与正常的习惯相反
5. 设置对应的显示级别
